version: "3"
services:
    backend:
        build: ./backend
        ports:
            - "3000:3000"
        volumes:
            - ./backend:/backend
    frontend:
        build: ./frontend
        ports:
            - "80:80"
        volumes:
            - ./frontend:/frontend
        depends_on:
            - backend
